- hosts: all
  become: yes
  user: "{{ user }}"
  vars_files:
    - vars/vars.yml
  gather_facts: no
  roles:
  - { role: Install, tags: ["install-basics"]  }

- hosts: app2
  become: yes
  user: "{{ user }}"
  vars_files:
    - vars/vars.yml
  gather_facts: no
  roles:
  - { role: Import, tags: ["import-files"] }